//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace boulzar.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("boulzar.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vAkAAB+LCAAAAAAABACVld9vmzAQx98n7X84Ie1tUjqp7UNGkVKaRWghiRJaqX2JHHDBHWBkm07pXz/bEGJ+RGUvJNi+z/nuvnfYAh1SDFwcU3xn/SWRSKY3V98s5+sXWzD5BLCTH45Nshg4C++sCAk0JRmK8aTI458HxPHt9Xd1Tp6kPKUxdSwLNOnOurmyACbOusAMCZJLxpELnNkTyVQeEmeFMjwFeyL/qoXIATuXS45aitTSRF/Drp+J84QZJzSHqXJomr1XG5ctNykS9JWyrGW2Wc6CX+utP2wnfRg+d4KpIACmNUJtG765tDlh9O1OiOq3gvnojTKoLUDF0cBOuAy97bvhABhEk1lR70uSRsa9zrCD2hnEtYANUtEIh9vrAxHQlKaGESpXb6/PmBPhnDCdQaUq+aZWLwqslZjRIpNnw6Ic1hn4KExIDi7NCprjXPBaaafMq10MSmBGZKek71vCG6ifYribR1CabRnbcnW/mvlz57PiK3M3peGf [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string source {
            get {
                return ResourceManager.GetString("source", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WJ0BAB+LCAAAAAAABADUvVt/ujrQKPyBelHb2tZeJiEcRQtqFe8UFfCErW2Rfvo9MwmIrWut53nffbO7fv+FQI6TyZwyMwzf3gPGfAZ/Ev93e9thrJuw6i9g/7s/VbO9+kra7JPte8484UO/lb5Z6SEueRHvXvbxzvx0rF463z1+LwTPpgNeLsbtZAb/QvkydKy776k1+jKClufWLfMghMEMmTSY9SHtnTx32mfMSVgXXjImCg7/d6pXs03Aq2FFNEV+Hmai79Sfdf4pEpp4DQaHRc5IFdYVZAUwxi4aUfepZAF/1a1y5gXmPwLMwdoF/DCSIJHM/seC//2Hkxa/ngl8IJNfDx9b00nawp9jcazh06UZOezPH7Zhsa943ysjHKqej4JnhD+//iKKAlZ3727n1suaaSRT81XD7DH5uxI1EyR/HmNbfliVV/OBNkZs70INp/zUHbIOjI9nqWCBaF9r5X/0JyLhcZxXDr9z7LoACD1WA5QBv8Er50O45lZX [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string STLR {
            get {
                return ResourceManager.GetString("STLR", resourceCulture);
            }
        }
    }
}
