//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace server.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("server.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _001_left_arrow {
            get {
                object obj = ResourceManager.GetObject("001-left-arrow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _001_screenshot {
            get {
                object obj = ResourceManager.GetObject("001-screenshot", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _002_close {
            get {
                object obj = ResourceManager.GetObject("002-close", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _002_right_arrow {
            get {
                object obj = ResourceManager.GetObject("002-right-arrow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _003_refresh_button {
            get {
                object obj = ResourceManager.GetObject("003-refresh-button", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _004_spyware {
            get {
                object obj = ResourceManager.GetObject("004-spyware", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap cat_what {
            get {
                object obj = ResourceManager.GetObject("cat-what", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap computer1 {
            get {
                object obj = ResourceManager.GetObject("computer1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap download {
            get {
                object obj = ResourceManager.GetObject("download", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///
        ///&lt;style&gt;
        ///  body {
        ///   
        ///    margin: auto;
        ///    background-color: #04243d;
        ///    font-family: &quot;Segoe UI&quot;, Tahoma, Geneva, Verdana, sans-serif;
        ///    color: white;
        ///  }
        ///  table{
        ///    margin: auto;
        ///    width: auto;
        ///    border: 1px solid black;
        ///  }
        ///th {
        ///  border: 1px solid rgb(177, 177, 177);
        ///  background-color: #0b4774ee;
        ///  padding: 12px;
        ///  font-size: large;
        ///}
        ///tr{
        ///  background-color:#0b477459;
        ///  font-size: large;
        ///}
        ///td{
        ///  border: 1px solid rgb(177, 177, 177);
        ///}
        ///&lt;/style&gt;
        ///&lt;body [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string html_clip_key {
            get {
                return ResourceManager.GetString("html_clip_key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html&gt;
        ///&lt;head&gt;
        /// &lt;style&gt;
        ///body{
        ///  background-color: #04243dee;
        ///  font-family: &apos;Segoe UI&apos;, Tahoma, Geneva, Verdana, sans-serif;
        /// 
        ///
        ///}
        ///table{
        ///  width: 100%;
        /// 
        ///  border-radius: 5px;
        ///  color: white;
        ///}
        ///th{
        /// 
        ///  background-color: rgba(58, 12, 226, 0.507);
        ///  width: 200px;
        ///                                                         
        ///  border: 1px solid rgb(0, 0, 0);
        ///}                              
        ///td {
        ///  
        ///  border-collapse: collapse;
        ///  }
        ///
        ///th, td {
        ///padding: 5px;
        ///text-align: left [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string html_info {
            get {
                return ResourceManager.GetString("html_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string html_info_geologo {
            get {
                return ResourceManager.GetString("html_info_geologo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap index__1_ {
            get {
                object obj = ResourceManager.GetObject("index (1)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream inflicted_601 {
            get {
                return ResourceManager.GetStream("inflicted_601", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html lang=&quot;en&quot;&gt;
        ///  &lt;head&gt;
        ///    &lt;meta charset=&quot;UTF-8&quot; /&gt;
        ///    &lt;meta http-equiv=&quot;X-UA-Compatible&quot; content=&quot;IE=edge&quot; /&gt;
        ///    &lt;meta name=&quot;viewport&quot; content=&quot;width=device-width, initial-scale=1.0&quot; /&gt;
        ///    &lt;title&gt;Keylogs&lt;/title&gt;
        ///  &lt;/head&gt;
        ///  &lt;body&gt;
        ///    &lt;style&gt;
        ///      body {
        ///   
        ///    margin: auto;
        ///    background-color: #04243d;
        ///    font-family: &quot;Segoe UI&quot;, Tahoma, Geneva, Verdana, sans-serif;
        ///    color: white;
        ///  }
        ///
        ///      kbd {
        ///        margin: 2px;
        ///        padding: 3px;
        ///        border- [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string keylogs_html {
            get {
                return ResourceManager.GetString("keylogs_html", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap shield {
            get {
                object obj = ResourceManager.GetObject("shield", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
